// vite.config.ts
import { defineConfig, type PluginOption } from 'vite';
import react from '@vitejs/plugin-react';
// Use named export for visualizer plugin
import { visualizer } from 'rollup-plugin-visualizer';
// PWA support for offline caching
// Import from dist for proper ESM resolution per package exports
import { VitePWA } from 'vite-plugin-pwa/dist/index.js';

function resolveApiBaseUrl(): string | undefined {
  const explicitDev = process.env.VITE_API_BASE_URL_DEV;
  if (explicitDev && explicitDev.trim().length > 0) {
    return explicitDev.trim();
  }
  return process.env.VITE_API_BASE_URL;
}

// Ensure Vite sees the correct API base at build time
const resolvedApiBase = resolveApiBaseUrl();
if (resolvedApiBase) {
  process.env.VITE_API_BASE_URL = resolvedApiBase;
}

export default defineConfig({
  // Include 'react-is' to satisfy recharts peer dependency
  optimizeDeps: {
    include: ['react-is'],
  },
  plugins: [
    react(),
    // Only include visualizer in development to reduce build memory usage
    ...(process.env.NODE_ENV === 'development' ? [
      visualizer({ filename: 'bundle-stats.html', open: false, gzipSize: true, brotliSize: true }) as unknown as PluginOption
    ] : []),
    // PWA support for offline caching and install prompt
    VitePWA({
      registerType: 'autoUpdate',
      workbox: {
        // Precache app shell assets generated by Vite
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2}'],
        // Offline fallback for navigation requests
        navigateFallback: '/index.html',
        navigateFallbackDenylist: [/^\/api\//],
        runtimeCaching: [
          // Cache-first for images
          {
            urlPattern: /\.(?:png|jpg|jpeg|svg|gif|webp|ico)$/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'images',
              expiration: { maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 },
            },
          },
          // Cache-first for fonts
          {
            urlPattern: /\.(?:woff|woff2|ttf|eot)$/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'fonts',
              expiration: { maxEntries: 20, maxAgeSeconds: 365 * 24 * 60 * 60 },
            },
          },
          // Network-first for API calls (loyalty, orders, manifest)
          {
            urlPattern: /^https?:\/\/[^/]+\/api\//,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'api-cache',
              networkTimeoutSeconds: 5,
              expiration: { maxEntries: 100, maxAgeSeconds: 24 * 60 * 60 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
      includeAssets: ['favicon.svg', 'robots.txt', 'offline.html'],
      manifest: {
        name: 'SMB Loyalty',
        short_name: 'SMB',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        background_color: '#ffffff',
        theme_color: '#667eea',
        icons: [
          { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' },
        ],
      },
    }),
  ],
  build: {
    // Optimize build for memory efficiency
    target: 'esnext',
    minify: 'esbuild',
    sourcemap: false, // Disable sourcemaps to reduce memory usage
    chunkSizeWarningLimit: 1000,
    cssCodeSplit: false,
  },
  server: {
    // Temporarily remove COOP header to test popup behavior
    headers: {
      // "Cross-Origin-Opener-Policy": "same-origin",
      // "Cross-Origin-Embedder-Policy": "require-corp", // Already commented out to allow Yoco SDK
    },
    host: true,
    proxy: {
      "/api": {
        target: "http://127.0.0.1:8000",
        changeOrigin: true,
      },
    },
  },
});
