version: '3.9'

services:
  backend:
    image: ghcr.io/dalingcebo1/smb-loyalty-backend:${BACKEND_TAG:-latest}
    restart: always
    env_file:
      - Backend/.env  # Provide sanitized file with real values in deploy environment
    environment:
      # These may override or supplement env_file (leave blank if not needed)
      - ENVIRONMENT=production
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ghcr.io/dalingcebo1/smb-loyalty-frontend:${FRONTEND_TAG:-latest}
    restart: always
    environment:
      - VITE_API_BASE_URL=${PUBLIC_API_BASE_URL}
      - VITE_ENVIRONMENT=production
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_prod_data:
