[tool.ruff]
line-length = 100
select = ["E","F","I","B","UP","SIM","ASYNC"]
ignore = ["E501"]
exclude = ["Backend/app/alembic/*", "_legacy_backup/*"]

[tool.ruff.isort]
known-first-party = ["app","config"]

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
ignore_missing_imports = true  # TODO: Gradually remove by adding explicit stubs or per-module ignores.
warn_unused_ignores = true
show_error_codes = true
namespace_packages = true
exclude = ["_legacy_backup/"]

[tool.coverage.run]
branch = true
source = ["Backend/app", "Backend"]

# Per-module stricter settings (mypy doesn't support arbitrary table names with dashes; use overrides)
[[tool.mypy.overrides]]
module = ["app.plugins.payments.*"]
disallow_untyped_defs = true
disallow_any_generics = true
warn_return_any = true
warn_unused_ignores = true
no_implicit_optional = true
strict_equality = true

# Gradual strict rollout for auth modules
[[tool.mypy.overrides]]
module = ["app.plugins.auth.*"]
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
strict_equality = true

# Gradual strict rollout for users modules
[[tool.mypy.overrides]]
module = ["app.plugins.users.*"]
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
strict_equality = true

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
