"""add_beauty_salon_models

Revision ID: 38104d9314b0
Revises: 476e4d5e7b78
Create Date: 2026-02-05 10:58:01.539367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38104d9314b0'
down_revision: Union[str, None] = '476e4d5e7b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beauty_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=True),
    sa.Column('requires_deposit', sa.Boolean(), nullable=True),
    sa.Column('deposit_cents', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('online_booking_enabled', sa.Boolean(), nullable=True),
    sa.Column('points_multiplier', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beauty_services_id'), 'beauty_services', ['id'], unique=False)
    op.create_index('ix_beauty_services_tenant_category', 'beauty_services', ['tenant_id', 'category'], unique=False)
    op.create_index(op.f('ix_beauty_services_tenant_id'), 'beauty_services', ['tenant_id'], unique=False)
    op.create_table('stylists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('accepts_walk_ins', sa.Boolean(), nullable=True),
    sa.Column('online_booking_enabled', sa.Boolean(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stylists_id'), 'stylists', ['id'], unique=False)
    op.create_index('ix_stylists_tenant_active', 'stylists', ['tenant_id', 'active'], unique=False)
    op.create_index(op.f('ix_stylists_tenant_id'), 'stylists', ['tenant_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('stylist_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('deposit_paid_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['beauty_services.id'], ),
    sa.ForeignKeyConstraint(['stylist_id'], ['stylists.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_service_id'), 'appointments', ['service_id'], unique=False)
    op.create_index('ix_appointments_status', 'appointments', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_appointments_stylist_date', 'appointments', ['stylist_id', 'appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_stylist_id'), 'appointments', ['stylist_id'], unique=False)
    op.create_index('ix_appointments_tenant_date', 'appointments', ['tenant_id', 'appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    op.create_table('stylist_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stylist_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('specific_date', sa.Date(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stylist_id'], ['stylists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stylist_availability_date', 'stylist_availability', ['stylist_id', 'specific_date'], unique=False)
    op.create_index('ix_stylist_availability_day', 'stylist_availability', ['stylist_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_stylist_availability_id'), 'stylist_availability', ['id'], unique=False)
    op.create_index(op.f('ix_stylist_availability_stylist_id'), 'stylist_availability', ['stylist_id'], unique=False)
    op.create_table('stylist_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stylist_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('custom_price_cents', sa.Integer(), nullable=True),
    sa.Column('custom_duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['beauty_services.id'], ),
    sa.ForeignKeyConstraint(['stylist_id'], ['stylists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stylist_id', 'service_id', name='uq_stylist_service')
    )
    op.create_index(op.f('ix_stylist_services_id'), 'stylist_services', ['id'], unique=False)
    op.create_index(op.f('ix_stylist_services_service_id'), 'stylist_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_stylist_services_stylist_id'), 'stylist_services', ['stylist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stylist_services_stylist_id'), table_name='stylist_services')
    op.drop_index(op.f('ix_stylist_services_service_id'), table_name='stylist_services')
    op.drop_index(op.f('ix_stylist_services_id'), table_name='stylist_services')
    op.drop_table('stylist_services')
    op.drop_index(op.f('ix_stylist_availability_stylist_id'), table_name='stylist_availability')
    op.drop_index(op.f('ix_stylist_availability_id'), table_name='stylist_availability')
    op.drop_index('ix_stylist_availability_day', table_name='stylist_availability')
    op.drop_index('ix_stylist_availability_date', table_name='stylist_availability')
    op.drop_table('stylist_availability')
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_index('ix_appointments_tenant_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_stylist_id'), table_name='appointments')
    op.drop_index('ix_appointments_stylist_date', table_name='appointments')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.drop_index(op.f('ix_appointments_service_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_stylists_tenant_id'), table_name='stylists')
    op.drop_index('ix_stylists_tenant_active', table_name='stylists')
    op.drop_index(op.f('ix_stylists_id'), table_name='stylists')
    op.drop_table('stylists')
    op.drop_index(op.f('ix_beauty_services_tenant_id'), table_name='beauty_services')
    op.drop_index('ix_beauty_services_tenant_category', table_name='beauty_services')
    op.drop_index(op.f('ix_beauty_services_id'), table_name='beauty_services')
    op.drop_table('beauty_services')
    # ### end Alembic commands ###
