"""Add missing subscription columns

Revision ID: ac2175519b17
Revises: 79b1837424d4
Create Date: 2025-12-05 10:40:54.755099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac2175519b17'
down_revision: Union[str, None] = '79b1837424d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('currency_name', sa.String(), nullable=True),
    sa.Column('accrual_ratio', sa.Float(), nullable=True),
    sa.Column('redemption_ratio', sa.Float(), nullable=True),
    sa.Column('points_expiry_days', sa.Integer(), nullable=True),
    sa.Column('tiers_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('loyalty_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_points', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['loyalty_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_transactions_tenant_id'), 'loyalty_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_user_id'), 'loyalty_transactions', ['user_id'], unique=False)
    op.alter_column('aggregated_customer_metrics', 'lifetime_washes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'lifetime_revenue',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'washes_30d',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'washes_90d',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'revenue_30d',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'revenue_90d',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'loyalty_washes_total',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'loyalty_washes_30d',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'points_redeemed_total',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'points_outstanding',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'points_redeemed_30d',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'r_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'f_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'm_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_acm_last_visit'), table_name='aggregated_customer_metrics')
    op.drop_index(op.f('ix_acm_segment'), table_name='aggregated_customer_metrics')
    op.create_foreign_key(None, 'aggregated_customer_metrics', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'aggregated_customer_metrics', 'users', ['user_id'], ['id'])
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_audit_logs_tenant_action_created'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_tenant_priority_actions'), table_name='audit_logs', postgresql_where="((action)::text = ANY ((ARRAY['user_login'::character varying, 'user_logout'::character varying, 'order_created'::character varying, 'payment_processed'::character varying])::text[]))")
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications', postgresql_where='(read_at IS NULL)')
    op.drop_index(op.f('ix_order_vehicles_order_vehicle'), table_name='order_vehicles')
    op.drop_index(op.f('ix_orders_active_tenant_created'), table_name='orders', postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'ready'::character varying])::text[]))")
    op.drop_index(op.f('ix_orders_completed_tenant_created'), table_name='orders', postgresql_where="((status)::text = 'completed'::text)")
    op.drop_index(op.f('ix_orders_ended_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_started_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_started_at_notnull'), table_name='orders', postgresql_where='(started_at IS NOT NULL)')
    op.drop_index(op.f('ix_orders_tenant_status_created'), table_name='orders')
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_foreign_key(None, 'orders', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_status_created_at'), table_name='payments')
    # Add reference column if it doesn't exist (may already exist in some databases)
    # Use batch operations to check and add column safely
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('payments')]
    if 'reference' not in columns:
        op.add_column('payments', sa.Column('reference', sa.String(), nullable=True))
    # Now add unique constraint on reference column
    op.create_unique_constraint(None, 'payments', ['reference'])
    op.add_column('point_balances', sa.Column('lifetime_points', sa.Integer(), nullable=True))
    op.add_column('point_balances', sa.Column('tier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'point_balances', 'loyalty_tiers', ['tier_id'], ['id'])
    op.drop_index(op.f('ix_redemptions_tenant_created'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_tenant_redeemed'), table_name='redemptions', postgresql_where='(redeemed_at IS NOT NULL)')
    op.create_foreign_key(None, 'redemptions', 'orders', ['order_id'], ['id'])
    op.create_index(op.f('ix_rewards_id'), 'rewards', ['id'], unique=False)
    op.create_foreign_key(None, 'rewards', 'services', ['service_id'], ['id'])
    op.drop_column('rewards', 'status')
    op.alter_column('services', 'loyalty_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('tenant_branding_tenant_id_fkey'), 'tenant_branding', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_branding', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('tenant_domains_domain_key'), 'tenant_domains', type_='unique')
    op.drop_index(op.f('ix_tenant_domains_domain'), table_name='tenant_domains')
    op.create_index(op.f('ix_tenant_domains_domain'), 'tenant_domains', ['domain'], unique=True)
    op.add_column('tenants', sa.Column('subscription_plan_id', sa.String(), nullable=False, server_default='free'))
    op.add_column('tenants', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tenants_stripe_customer_id'), 'tenants', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_tenants_stripe_subscription_id'), 'tenants', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_tenants_vertical_type'), 'tenants', ['vertical_type'], unique=False)
    op.create_unique_constraint(None, 'tenants', ['primary_domain'])
    op.drop_index(op.f('ix_users_tenant_regular'), table_name='users', postgresql_where="((role)::text = 'user'::text)")
    op.drop_index(op.f('ix_users_tenant_staff'), table_name='users', postgresql_where="((role)::text = ANY ((ARRAY['staff'::character varying, 'admin'::character varying])::text[]))")
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_tenant_staff'), 'users', ['tenant_id', 'created_at'], unique=False, postgresql_where="((role)::text = ANY ((ARRAY['staff'::character varying, 'admin'::character varying])::text[]))")
    op.create_index(op.f('ix_users_tenant_regular'), 'users', ['tenant_id', 'created_at'], unique=False, postgresql_where="((role)::text = 'user'::text)")
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_vertical_type'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_stripe_subscription_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_stripe_customer_id'), table_name='tenants')
    op.drop_column('tenants', 'stripe_subscription_id')
    op.drop_column('tenants', 'stripe_customer_id')
    op.drop_column('tenants', 'subscription_status')
    op.drop_column('tenants', 'subscription_plan_id')
    op.drop_index(op.f('ix_tenant_domains_domain'), table_name='tenant_domains')
    op.create_index(op.f('ix_tenant_domains_domain'), 'tenant_domains', ['domain'], unique=False)
    op.create_unique_constraint(op.f('tenant_domains_domain_key'), 'tenant_domains', ['domain'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'tenant_branding', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_branding_tenant_id_fkey'), 'tenant_branding', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('services', 'loyalty_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('rewards', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rewards', type_='foreignkey')
    op.drop_index(op.f('ix_rewards_id'), table_name='rewards')
    op.drop_constraint(None, 'redemptions', type_='foreignkey')
    op.create_index(op.f('ix_redemptions_tenant_redeemed'), 'redemptions', ['tenant_id', 'created_at'], unique=False, postgresql_where='(redeemed_at IS NOT NULL)')
    op.create_index(op.f('ix_redemptions_tenant_created'), 'redemptions', ['tenant_id', 'created_at'], unique=False)
    op.drop_constraint(None, 'point_balances', type_='foreignkey')
    op.drop_column('point_balances', 'tier_id')
    op.drop_column('point_balances', 'lifetime_points')
    op.drop_constraint(None, 'payments', type_='unique')
    # Drop reference column if it was added by this migration
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('payments')]
    if 'reference' in columns:
        op.drop_column('payments', 'reference')
    op.create_index(op.f('ix_payments_status_created_at'), 'payments', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.create_index(op.f('ix_orders_tenant_status_created'), 'orders', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_started_at_notnull'), 'orders', ['started_at'], unique=False, postgresql_where='(started_at IS NOT NULL)')
    op.create_index(op.f('ix_orders_started_at'), 'orders', ['started_at'], unique=False)
    op.create_index(op.f('ix_orders_ended_at'), 'orders', ['ended_at'], unique=False)
    op.create_index(op.f('ix_orders_completed_tenant_created'), 'orders', ['tenant_id', 'created_at'], unique=False, postgresql_where="((status)::text = 'completed'::text)")
    op.create_index(op.f('ix_orders_active_tenant_created'), 'orders', ['tenant_id', 'created_at'], unique=False, postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'ready'::character varying])::text[]))")
    op.create_index(op.f('ix_order_vehicles_order_vehicle'), 'order_vehicles', ['order_id', 'vehicle_id'], unique=True)
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where='(read_at IS NULL)')
    op.create_index(op.f('ix_notifications_user_created'), 'notifications', ['user_id', 'created_at'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_audit_tenant_priority_actions'), 'audit_logs', ['tenant_id', 'created_at', 'action'], unique=False, postgresql_where="((action)::text = ANY ((ARRAY['user_login'::character varying, 'user_logout'::character varying, 'order_created'::character varying, 'payment_processed'::character varying])::text[]))")
    op.create_index(op.f('ix_audit_logs_tenant_action_created'), 'audit_logs', ['tenant_id', 'action', 'created_at'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'aggregated_customer_metrics', type_='foreignkey')
    op.drop_constraint(None, 'aggregated_customer_metrics', type_='foreignkey')
    op.create_index(op.f('ix_acm_segment'), 'aggregated_customer_metrics', ['segment'], unique=False)
    op.create_index(op.f('ix_acm_last_visit'), 'aggregated_customer_metrics', ['last_visit_at'], unique=False)
    op.alter_column('aggregated_customer_metrics', 'm_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'f_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'r_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'points_redeemed_30d',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'points_outstanding',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'points_redeemed_total',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'loyalty_washes_30d',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'loyalty_washes_total',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'revenue_90d',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'revenue_30d',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'washes_90d',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'washes_30d',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'lifetime_revenue',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('aggregated_customer_metrics', 'lifetime_washes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_loyalty_transactions_user_id'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_tenant_id'), table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_table('loyalty_tiers')
    op.drop_table('loyalty_programs')
    # ### end Alembic commands ###
