"""add_financial_tools_invoices_expenses

Revision ID: c341012934cf
Revises: cbc01d7712ac
Create Date: 2026-02-06 09:59:25.855781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c341012934cf'
down_revision: Union[str, None] = 'cbc01d7712ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.drop_index(op.f('ix_flower_orders_order_number'), table_name='flower_orders')
    op.create_index(op.f('ix_flower_orders_order_number'), 'flower_orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flower_orders_order_number'), table_name='flower_orders')
    op.create_index(op.f('ix_flower_orders_order_number'), 'flower_orders', ['order_number'], unique=False)
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###
