"""add_marketing_campaigns

Revision ID: cbc01d7712ac
Revises: 9c93a6f761be
Create Date: 2026-02-06 09:38:51.741989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc01d7712ac'
down_revision: Union[str, None] = '9c93a6f761be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('campaign_type', sa.Enum('EMAIL', 'SMS', 'PUSH', name='campaigntype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'FAILED', 'CANCELLED', name='campaignstatus'), nullable=False),
    sa.Column('segment_type', sa.Enum('ALL', 'HIGH_VALUE', 'DORMANT', 'NEW', 'BIRTHDAY', 'LOYALTY_TIER', 'CUSTOM', name='segmenttype'), nullable=False),
    sa.Column('segment_config', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('delivered_count', sa.Integer(), nullable=True),
    sa.Column('opened_count', sa.Integer(), nullable=True),
    sa.Column('clicked_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_type'), 'campaigns', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_campaigns_created_at'), 'campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index('ix_campaigns_scheduled', 'campaigns', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_index('ix_campaigns_tenant_status', 'campaigns', ['tenant_id', 'status'], unique=False)
    op.create_table('customer_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('segment_type', sa.Enum('ALL', 'HIGH_VALUE', 'DORMANT', 'NEW', 'BIRTHDAY', 'LOYALTY_TIER', 'CUSTOM', name='segmenttype'), nullable=False),
    sa.Column('filter_config', sa.JSON(), nullable=True),
    sa.Column('customer_count', sa.Integer(), nullable=True),
    sa.Column('last_computed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_segments_id'), 'customer_segments', ['id'], unique=False)
    op.create_index(op.f('ix_customer_segments_tenant_id'), 'customer_segments', ['tenant_id'], unique=False)
    op.create_index('ix_segments_tenant', 'customer_segments', ['tenant_id'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_index('ix_campaign_recipients_customer', 'campaign_recipients', ['customer_id', 'campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_customer_id'), 'campaign_recipients', ['customer_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_id'), 'campaign_recipients', ['id'], unique=False)
    op.create_index('ix_campaign_recipients_status', 'campaign_recipients', ['sent_at', 'delivered_at'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_tenant_id'), 'campaign_recipients', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.create_index('ix_appointments_status', 'appointments', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_beauty_appointment_reminders_appointment_id'), 'beauty_appointment_reminders', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_beauty_appointment_reminders_customer_id'), 'beauty_appointment_reminders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_beauty_appointment_reminders_id'), 'beauty_appointment_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_beauty_appointment_reminders_status'), 'beauty_appointment_reminders', ['status'], unique=False)
    op.create_index(op.f('ix_beauty_appointment_reminders_tenant_id'), 'beauty_appointment_reminders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_beauty_package_bookings_customer_id'), 'beauty_package_bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_beauty_package_bookings_id'), 'beauty_package_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_beauty_package_bookings_package_id'), 'beauty_package_bookings', ['package_id'], unique=False)
    op.create_index(op.f('ix_beauty_package_bookings_status'), 'beauty_package_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_beauty_package_bookings_tenant_id'), 'beauty_package_bookings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_beauty_packages_id'), 'beauty_packages', ['id'], unique=False)
    op.create_index(op.f('ix_beauty_packages_tenant_id'), 'beauty_packages', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('beauty_service_reviews_appointment_id_key'), 'beauty_service_reviews', type_='unique')
    op.create_index(op.f('ix_beauty_service_reviews_appointment_id'), 'beauty_service_reviews', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_beauty_service_reviews_approved'), 'beauty_service_reviews', ['approved'], unique=False)
    op.create_index(op.f('ix_beauty_service_reviews_customer_id'), 'beauty_service_reviews', ['customer_id'], unique=False)
    op.create_index(op.f('ix_beauty_service_reviews_id'), 'beauty_service_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_beauty_service_reviews_service_id'), 'beauty_service_reviews', ['service_id'], unique=False)
    op.create_index(op.f('ix_beauty_service_reviews_stylist_id'), 'beauty_service_reviews', ['stylist_id'], unique=False)
    op.create_index(op.f('ix_beauty_service_reviews_tenant_id'), 'beauty_service_reviews', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_flower_orders_order_number'), table_name='flower_orders')
    op.create_index('ix_flower_orders_order_number', 'flower_orders', ['order_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flower_orders_order_number', table_name='flower_orders')
    op.create_index(op.f('ix_flower_orders_order_number'), 'flower_orders', ['order_number'], unique=True)
    op.drop_index(op.f('ix_beauty_service_reviews_tenant_id'), table_name='beauty_service_reviews')
    op.drop_index(op.f('ix_beauty_service_reviews_stylist_id'), table_name='beauty_service_reviews')
    op.drop_index(op.f('ix_beauty_service_reviews_service_id'), table_name='beauty_service_reviews')
    op.drop_index(op.f('ix_beauty_service_reviews_id'), table_name='beauty_service_reviews')
    op.drop_index(op.f('ix_beauty_service_reviews_customer_id'), table_name='beauty_service_reviews')
    op.drop_index(op.f('ix_beauty_service_reviews_approved'), table_name='beauty_service_reviews')
    op.drop_index(op.f('ix_beauty_service_reviews_appointment_id'), table_name='beauty_service_reviews')
    op.create_unique_constraint(op.f('beauty_service_reviews_appointment_id_key'), 'beauty_service_reviews', ['appointment_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_beauty_packages_tenant_id'), table_name='beauty_packages')
    op.drop_index(op.f('ix_beauty_packages_id'), table_name='beauty_packages')
    op.drop_index(op.f('ix_beauty_package_bookings_tenant_id'), table_name='beauty_package_bookings')
    op.drop_index(op.f('ix_beauty_package_bookings_status'), table_name='beauty_package_bookings')
    op.drop_index(op.f('ix_beauty_package_bookings_package_id'), table_name='beauty_package_bookings')
    op.drop_index(op.f('ix_beauty_package_bookings_id'), table_name='beauty_package_bookings')
    op.drop_index(op.f('ix_beauty_package_bookings_customer_id'), table_name='beauty_package_bookings')
    op.drop_index(op.f('ix_beauty_appointment_reminders_tenant_id'), table_name='beauty_appointment_reminders')
    op.drop_index(op.f('ix_beauty_appointment_reminders_status'), table_name='beauty_appointment_reminders')
    op.drop_index(op.f('ix_beauty_appointment_reminders_id'), table_name='beauty_appointment_reminders')
    op.drop_index(op.f('ix_beauty_appointment_reminders_customer_id'), table_name='beauty_appointment_reminders')
    op.drop_index(op.f('ix_beauty_appointment_reminders_appointment_id'), table_name='beauty_appointment_reminders')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.drop_index(op.f('ix_campaign_recipients_tenant_id'), table_name='campaign_recipients')
    op.drop_index('ix_campaign_recipients_status', table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_customer_id'), table_name='campaign_recipients')
    op.drop_index('ix_campaign_recipients_customer', table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index('ix_segments_tenant', table_name='customer_segments')
    op.drop_index(op.f('ix_customer_segments_tenant_id'), table_name='customer_segments')
    op.drop_index(op.f('ix_customer_segments_id'), table_name='customer_segments')
    op.drop_table('customer_segments')
    op.drop_index('ix_campaigns_tenant_status', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index('ix_campaigns_scheduled', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_created_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_type'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
