"""add_dispensary_models

Revision ID: f288af129ebb
Revises: ff5dddfd0fab
Create Date: 2026-02-05 13:08:50.094394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f288af129ebb'
down_revision: Union[str, None] = 'ff5dddfd0fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###
