"""add_flowershop_models

Revision ID: ff5dddfd0fab
Revises: fb26681fb449
Create Date: 2026-02-05 12:51:33.451617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5dddfd0fab'
down_revision: Union[str, None] = 'fb26681fb449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=50), nullable=False),
    sa.Column('max_deliveries', sa.Integer(), nullable=True),
    sa.Column('current_bookings', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('fee_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'delivery_date', 'time_slot', name='uq_delivery_slot_per_tenant')
    )
    op.create_index('ix_delivery_slots_date', 'delivery_slots', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_delivery_slots_delivery_date'), 'delivery_slots', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_delivery_slots_id'), 'delivery_slots', ['id'], unique=False)
    op.create_index('ix_delivery_slots_tenant', 'delivery_slots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_delivery_slots_tenant_id'), 'delivery_slots', ['tenant_id'], unique=False)
    op.create_table('flower_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_flower_category_name_per_tenant')
    )
    op.create_index(op.f('ix_flower_categories_id'), 'flower_categories', ['id'], unique=False)
    op.create_index('ix_flower_categories_tenant', 'flower_categories', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_flower_categories_tenant_id'), 'flower_categories', ['tenant_id'], unique=False)
    op.create_table('flower_occasions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color_scheme', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flower_occasions_id'), 'flower_occasions', ['id'], unique=False)
    op.create_index('ix_flower_occasions_tenant', 'flower_occasions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_flower_occasions_tenant_id'), 'flower_occasions', ['tenant_id'], unique=False)
    op.create_table('flower_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_type', sa.String(length=20), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('delivery_time_slot', sa.String(length=50), nullable=True),
    sa.Column('recipient_name', sa.String(length=200), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('delivery_address_line1', sa.String(length=200), nullable=True),
    sa.Column('delivery_address_line2', sa.String(length=200), nullable=True),
    sa.Column('delivery_city', sa.String(length=100), nullable=True),
    sa.Column('delivery_postal_code', sa.String(length=20), nullable=True),
    sa.Column('delivery_instructions', sa.Text(), nullable=True),
    sa.Column('gift_message', sa.Text(), nullable=True),
    sa.Column('include_sender_name', sa.Boolean(), nullable=True),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('delivery_fee_cents', sa.Integer(), nullable=True),
    sa.Column('discount_cents', sa.Integer(), nullable=True),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('loyalty_points_awarded', sa.Integer(), nullable=True),
    sa.Column('loyalty_points_awarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flower_orders_customer', 'flower_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_flower_orders_customer_id'), 'flower_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_flower_orders_delivery_date'), 'flower_orders', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_flower_orders_id'), 'flower_orders', ['id'], unique=False)
    op.create_index(op.f('ix_flower_orders_order_number'), 'flower_orders', ['order_number'], unique=True)
    op.create_index('ix_flower_orders_status', 'flower_orders', ['status'], unique=False)
    op.create_index('ix_flower_orders_tenant', 'flower_orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_flower_orders_tenant_id'), 'flower_orders', ['tenant_id'], unique=False)
    op.create_table('flower_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('sale_price_cents', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('track_inventory', sa.Boolean(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('color_scheme', sa.String(length=100), nullable=True),
    sa.Column('includes_vase', sa.Boolean(), nullable=True),
    sa.Column('includes_card', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('seasonal', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('available_for_delivery', sa.Boolean(), nullable=True),
    sa.Column('available_for_pickup', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['flower_categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flower_products_active_featured', 'flower_products', ['active', 'featured'], unique=False)
    op.create_index('ix_flower_products_category', 'flower_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_flower_products_category_id'), 'flower_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_flower_products_id'), 'flower_products', ['id'], unique=False)
    op.create_index('ix_flower_products_tenant', 'flower_products', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_flower_products_tenant_id'), 'flower_products', ['tenant_id'], unique=False)
    op.create_table('flower_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['flower_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['flower_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flower_order_items_id'), 'flower_order_items', ['id'], unique=False)
    op.create_index('ix_flower_order_items_order', 'flower_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_flower_order_items_order_id'), 'flower_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_flower_order_items_product_id'), 'flower_order_items', ['product_id'], unique=False)
    op.create_table('product_occasions',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('occasion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['occasion_id'], ['flower_occasions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['flower_products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'occasion_id')
    )
    op.create_index('ix_product_occasions_occasion', 'product_occasions', ['occasion_id'], unique=False)
    op.create_index('ix_product_occasions_product', 'product_occasions', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_occasions_product', table_name='product_occasions')
    op.drop_index('ix_product_occasions_occasion', table_name='product_occasions')
    op.drop_table('product_occasions')
    op.drop_index(op.f('ix_flower_order_items_product_id'), table_name='flower_order_items')
    op.drop_index(op.f('ix_flower_order_items_order_id'), table_name='flower_order_items')
    op.drop_index('ix_flower_order_items_order', table_name='flower_order_items')
    op.drop_index(op.f('ix_flower_order_items_id'), table_name='flower_order_items')
    op.drop_table('flower_order_items')
    op.drop_index(op.f('ix_flower_products_tenant_id'), table_name='flower_products')
    op.drop_index('ix_flower_products_tenant', table_name='flower_products')
    op.drop_index(op.f('ix_flower_products_id'), table_name='flower_products')
    op.drop_index(op.f('ix_flower_products_category_id'), table_name='flower_products')
    op.drop_index('ix_flower_products_category', table_name='flower_products')
    op.drop_index('ix_flower_products_active_featured', table_name='flower_products')
    op.drop_table('flower_products')
    op.drop_index(op.f('ix_flower_orders_tenant_id'), table_name='flower_orders')
    op.drop_index('ix_flower_orders_tenant', table_name='flower_orders')
    op.drop_index('ix_flower_orders_status', table_name='flower_orders')
    op.drop_index(op.f('ix_flower_orders_order_number'), table_name='flower_orders')
    op.drop_index(op.f('ix_flower_orders_id'), table_name='flower_orders')
    op.drop_index(op.f('ix_flower_orders_delivery_date'), table_name='flower_orders')
    op.drop_index(op.f('ix_flower_orders_customer_id'), table_name='flower_orders')
    op.drop_index('ix_flower_orders_customer', table_name='flower_orders')
    op.drop_table('flower_orders')
    op.drop_index(op.f('ix_flower_occasions_tenant_id'), table_name='flower_occasions')
    op.drop_index('ix_flower_occasions_tenant', table_name='flower_occasions')
    op.drop_index(op.f('ix_flower_occasions_id'), table_name='flower_occasions')
    op.drop_table('flower_occasions')
    op.drop_index(op.f('ix_flower_categories_tenant_id'), table_name='flower_categories')
    op.drop_index('ix_flower_categories_tenant', table_name='flower_categories')
    op.drop_index(op.f('ix_flower_categories_id'), table_name='flower_categories')
    op.drop_table('flower_categories')
    op.drop_index(op.f('ix_delivery_slots_tenant_id'), table_name='delivery_slots')
    op.drop_index('ix_delivery_slots_tenant', table_name='delivery_slots')
    op.drop_index(op.f('ix_delivery_slots_id'), table_name='delivery_slots')
    op.drop_index(op.f('ix_delivery_slots_delivery_date'), table_name='delivery_slots')
    op.drop_index('ix_delivery_slots_date', table_name='delivery_slots')
    op.drop_table('delivery_slots')
    # ### end Alembic commands ###
