name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Prefer npm – remove yarn.lock to avoid Yarn engine checks
        run: |
          rm -f Frontend/yarn.lock || true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_RIVER_01EDA360F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./Frontend" # App source code path
          output_location: "dist" # Vite build output
          app_build_command: |
            rm -f yarn.lock || true
            npm ci
            npm run build
          ###### End of Repository/Build Configurations ######
        env:
          VITE_API_BASE_URL: https://api.chaosx.co.za
          USE_NPM: "true"           # Hint Oryx to use npm
          NODE_VERSION: "20"
          WEBSITE_NODE_DEFAULT_VERSION: "~20"
          SWA_NODE_VERSION: "20"
          VITE_APP_VERSION: ${{ github.sha }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_RIVER_01EDA360F }}
          app_location: "./Frontend"
          output_location: "dist"
          action: "close"
