name: Deploy API (Azure Container Apps)

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'
      - '.github/workflows/backend-azure-containerapps.yml'
  workflow_dispatch:
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: SMB-Loyalty-Group
  CONTAINERAPP_NAME: apismbloyaltyapp
  ACR_NAME: smblpcontainerregistry
  IMAGE_NAME: smb-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Azure Container Apps extension
          run: |
            set -euo pipefail
            echo "Building $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} from Backend/Dockerfile"
            az acr build \
              -r "$ACR_NAME" \
              -t "$ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}" \
              -f Backend/Dockerfile Backend

        - name: Deploy image to Container App
          uses: azure/container-apps-deploy-action@v2
          with:
            resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
            containerAppName: ${{ env.CONTAINERAPP_NAME }}
            imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

        - name: Output app URL
          run: |
            fqdn=$(az containerapp show -g "$AZURE_RESOURCE_GROUP" -n "$CONTAINERAPP_NAME" --query properties.configuration.ingress.fqdn -o tsv)
            echo "API URL: https://$fqdn"

      - name: Build and push image to ACR (remote)
        run: |
          az acr build \
            -r $ACR_NAME \
            -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} \
            -f Backend/Dockerfile Backend

      - name: Deploy image to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINERAPP_NAME }}
          imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Output app URL
        run: |
          fqdn=$(az containerapp show -g "$AZURE_RESOURCE_GROUP" -n "$CONTAINERAPP_NAME" --query properties.configuration.ingress.fqdn -o tsv)
          echo "API URL: https://$fqdn"
