name: Backend CI

on:
  push:
    paths:
      - 'Backend/**'
  pull_request:
    paths:
      - 'Backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - '5432:5432'
        options: >-
          --health-cmd "pg_isready -U postgres -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt
      - name: Run migrations
        run: |
          alembic -c Backend/alembic.ini upgrade head
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 Backend
      - name: Type check with mypy
        run: |
          pip install mypy
          mypy Backend --ignore-missing-imports
      - name: Run tests with coverage
        run: |
          pip install pytest-cov
          pytest --cov=app --cov-report=term-missing --cov-report=xml:coverage.xml -v Backend/tests
