name: DISABLED - Legacy AWS Deploy (manual only)

on:
  # Keep only manual dispatch to avoid any automatic triggers
  workflow_dispatch:
    inputs:
      note:
        description: "This AWS workflow is disabled. Use Azure workflows instead (Container Apps, SWA)."
        required: false

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: |
          echo "This legacy AWS deployment workflow has been disabled."
          echo "Please use:"
          echo "- backend-azure-containerapps.yml for backend deployments"
          echo "- frontend-azure-swa.yml or azure-static-web-apps-*.yml for frontend"
