name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: cd Backend && pip install -r requirements.txt

      - name: Install frontend dependencies
        run: cd Frontend && npm ci
        
      - name: Install Cypress dependencies (Ubuntu 24.04)
        run: |
          sudo apt-get update
          # Noble (24.04) uses t64 packages and different names; avoid deprecated libs
          sudo apt-get install -y \
            xvfb \
            libgtk2.0-0 \
            libgtk-3-0 \
            libgbm1 \
            libnotify-dev \
            libnss3 \
            libxss1 \
            libasound2t64 \
            libxtst6 \
            xauth
      
      - name: Start backend server (FastAPI)
        run: |
          cd Backend
          export DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db
          export JWT_SECRET=test_secret
          nohup python -m uvicorn main:app --host 127.0.0.1 --port 8000 &

      - name: Wait for backend to be ready
        run: |
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:8000/health/ > /dev/null; then echo "Backend up"; exit 0; fi
            sleep 2
          done
          echo "Backend did not start in time"; exit 1

      - name: Build frontend
        run: |
          cd Frontend
          VITE_API_BASE_URL=http://127.0.0.1:8000 npm run build
      
      - name: Start frontend server (port 3000)
        run: cd Frontend && npm run preview -- --port 3000 &

      - name: Wait for frontend to be ready
        run: |
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:3000 > /dev/null; then echo "Frontend up"; exit 0; fi
            sleep 2
          done
          echo "Frontend did not start in time"; exit 1
        
      - name: Run Cypress tests
        run: |
          cd Frontend
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npm run cypress:run
