name: Release Frontend Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install deps
        run: cd Frontend && npm ci

      - name: Build
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL || secrets.CA_PUBLIC_API_URL }}
          VITE_APP_VERSION: ${{ github.ref_name }}
          VITE_YOCO_PUBLIC_KEY: ${{ vars.VITE_YOCO_PUBLIC_KEY || secrets.VITE_YOCO_PUBLIC_KEY }}
          VITE_FIREBASE_API_KEY: ${{ vars.VITE_FIREBASE_API_KEY || secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.VITE_FIREBASE_AUTH_DOMAIN || secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ vars.VITE_FIREBASE_PROJECT_ID || secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ vars.VITE_FIREBASE_STORAGE_BUCKET || secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.VITE_FIREBASE_MESSAGING_SENDER_ID || secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ vars.VITE_FIREBASE_APP_ID || secrets.VITE_FIREBASE_APP_ID }}
        run: cd Frontend && npm run build

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/smb-loyalty-frontend:${GITHUB_REF_NAME} -f Frontend/Dockerfile Frontend
          docker tag ghcr.io/${{ github.repository_owner }}/smb-loyalty-frontend:${GITHUB_REF_NAME} ghcr.io/${{ github.repository_owner }}/smb-loyalty-frontend:latest

      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/smb-loyalty-frontend:${GITHUB_REF_NAME}
          docker push ghcr.io/${{ github.repository_owner }}/smb-loyalty-frontend:latest

      - name: Summarize
        run: echo "Published frontend image version ${GITHUB_REF_NAME}" >> $GITHUB_STEP_SUMMARY
