name: Release Frontend Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install deps
        run: cd Frontend && npm ci

      - name: Build
        run: cd Frontend && npm run build

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/smb-loyalty-frontend:${GITHUB_REF_NAME} -f Frontend/Dockerfile Frontend
          docker tag ghcr.io/${{ github.repository_owner }}/smb-loyalty-frontend:${GITHUB_REF_NAME} ghcr.io/${{ github.repository_owner }}/smb-loyalty-frontend:latest

      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/smb-loyalty-frontend:${GITHUB_REF_NAME}
          docker push ghcr.io/${{ github.repository_owner }}/smb-loyalty-frontend:latest

      - name: Summarize
        run: echo "Published frontend image version ${GITHUB_REF_NAME}" >> $GITHUB_STEP_SUMMARY
